# Generated by Django 5.1.2 on 2024-11-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_data_created_at_alter_device_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data',
            table='data',
        ),
        migrations.AlterModelTable(
            name='device',
            table='devices',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
